// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_g7V3vuGcgYlbv_-dusLp_gdjEYO17es',
    appId: '1:626657882689:web:1c4dfbf3f2cd7dc77bccc0',
    messagingSenderId: '626657882689',
    projectId: 'audiora-fa05c',
    authDomain: 'audiora-fa05c.firebaseapp.com',
    storageBucket: 'audiora-fa05c.firebasestorage.app',
    measurementId: 'G-VJM92PDNPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdBvymWWXA0f2mJ2HO7Uq4DKBeQOEFu2U',
    appId: '1:626657882689:android:c01881d1e5fee5027bccc0',
    messagingSenderId: '626657882689',
    projectId: 'audiora-fa05c',
    storageBucket: 'audiora-fa05c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZn9IG-9OLszpw3OAFTckRZO4C9cMhxeE',
    appId: '1:626657882689:ios:be2fd74d5dd76bc07bccc0',
    messagingSenderId: '626657882689',
    projectId: 'audiora-fa05c',
    storageBucket: 'audiora-fa05c.firebasestorage.app',
    iosBundleId: 'com.example.melodyFlow',
  );
}
